swagger: "2.0"
info:
  description: This is the swagger yaml file
  version: "1.0.0"
  title: REST API
paths:
  /get-items:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Success
  /get:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Success
        "400":
          description: Invalid request
